"use client";
import React from 'react';

import {
  FileText,
  Download,
  CheckCircle2,
  Building2,
  Sparkles,
  ArrowRight,
  UserCheck
} from 'lucide-react';
import { motion } from 'framer-motion';
import { useRouter } from 'next/navigation';
import { MOCK_COORDINATOR_PATIENTS, MOCK_REHAB_CENTRES } from '@/lib/data';
import { DashboardShell } from '@/components/dashboard/DashboardShell';
import { RehabCentre } from '@/types/type';

export const PatientConsultationSummaryPage: React.FC = () => {
  const router = useRouter();
  const coordinator = MOCK_COORDINATOR_PATIENTS[0];

  return (
    <DashboardShell
      title="Clinical Recommendation Summary"
      description="Post-session assessment and personalized rehabilitation plan generated by Dr. Amara Okafor."
      breadcrumbs={[
        { label: 'Healthcare Portal', path: '/patient' },
        { label: 'Consultation Summary' },
      ]}
    >
      <div className="max-w-4xl mx-auto space-y-6">
        {/* Header Summary Banner */}
        <div className="p-6 rounded-3xl bg-[var(--background-secondary)] border border-[var(--border)] flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 shadow-xl">
          <div className="flex items-center gap-4">
            <img
              src={coordinator.avatar}
              alt={coordinator.name}
              className="w-14 h-14 rounded-2xl object-cover border border-[var(--border-subtle)]"
            />
            <div>
              <div className="flex items-center gap-2">
                <h3 className="font-cinzel font-bold text-base text-[var(--foreground)]">
                  {coordinator.name}
                </h3>
                <span className="px-2.5 py-0.5 rounded-full bg-[var(--gold)]/15 border border-[var(--gold)]/30 text-[var(--gold)] text-[10px] font-bold">
                  Care Lead
                </span>
              </div>
              <p className="text-xs text-[var(--foreground-muted)]">{coordinator.title}</p>
              <p className="text-[11px] text-[var(--gold)] font-semibold mt-0.5">Session Date: Aug 5, 2026</p>
            </div>
          </div>

          <button
            onClick={() => alert('Clinical PDF Summary report downloaded!')}
            className="px-5 py-2.5 rounded-xl bg-[var(--background-tertiary)] border border-[var(--border)] text-[var(--foreground)] hover:border-[var(--gold)] text-xs font-bold flex items-center gap-2 transition-colors shadow-sm"
          >
            <Download className="w-4 h-4 text-[var(--gold)]" />
            <span>Download PDF Report</span>
          </button>
        </div>

        {/* 2 COLUMN CONTENT */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Main Notes & Recommendation (2 Cols) */}
          <div className="lg:col-span-2 space-y-6">
            <div className="p-6 rounded-3xl bg-[var(--background-secondary)] border border-[var(--border)] space-y-4 shadow-xl">
              <h4 className="font-cinzel font-bold text-base text-[var(--foreground)] flex items-center gap-2">
                <FileText className="w-5 h-5 text-[var(--gold)]" />
                <span>Clinical Impressions & Diagnosis</span>
              </h4>
              <p className="text-xs text-[var(--foreground-muted)] leading-relaxed">
                Patient presents with post-surgical knee reconstruction stiffness and muscle atrophy following ligament repair. Good cognitive engagement and high motivation for structured physical therapy. No acute complications reported.
              </p>

              <h4 className="font-cinzel font-bold text-base text-[var(--foreground)] flex items-center gap-2 pt-2">
                <Sparkles className="w-5 h-5 text-[var(--gold)]" />
                <span>Recommended Recovery Pathway</span>
              </h4>
              <div className="p-4 rounded-2xl bg-[var(--background-tertiary)] border border-[var(--border-subtle)] space-y-2 text-xs text-[var(--foreground)]">
                <p className="font-bold text-[var(--gold)]">6-Week Inpatient / Intensive Outpatient Orthopedic Program</p>
                <ul className="list-disc pl-4 space-y-1 text-[var(--foreground-muted)]">
                  <li>Daily hydrotherapy & resistance movement training</li>
                  <li>Bi-weekly progress evaluation with orthopedic lead</li>
                  <li>Targeted quad strength restoration to 85% baseline</li>
                </ul>
              </div>
            </div>

            {/* RECOMMENDED REHABILITATION FACILITIES */}
            <div className="p-6 rounded-3xl bg-[var(--background-secondary)] border border-[var(--border)] space-y-4 shadow-xl">
              <h4 className="font-cinzel font-bold text-base text-[var(--foreground)] flex items-center gap-2">
                <Building2 className="w-5 h-5 text-[var(--gold)]" />
                <span>Matched Rehabilitation Sanctuaries</span>
              </h4>

              <div className="space-y-3">
                {MOCK_REHAB_CENTRES.map((centre) => (
                  <div
                    key={centre.id}
                    className="p-4 rounded-2xl bg-[var(--background-tertiary)] border border-[var(--border)] flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3 text-xs"
                  >
                    <div className="space-y-1">
                      <div className="flex items-center gap-2">
                        <span className="font-bold text-sm text-[var(--foreground)]">{centre.name}</span>
                        <span className="px-2 py-0.5 rounded-full bg-[var(--green)]/20 text-[var(--green)] border border-[var(--green)]/30 text-[10px] font-bold">
                          {centre.rating}★ Verified
                        </span>
                      </div>
                      <p className="text-[var(--foreground-muted)]">{centre.location} • {centre.accreditation}</p>
                    </div>

                    <button
                      onClick={() => router.push('/rehab-centers')}
                      className="px-4 py-2 rounded-xl bg-[var(--gold)] text-black font-bold text-xs hover:bg-[var(--gold-light)] flex items-center gap-1 shrink-0 transition-all hover:scale-105"
                    >
                      <span>Explore Facility</span>
                      <ArrowRight className="w-3.5 h-3.5" />
                    </button>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Right Column: Next Steps */}
          <div className="space-y-6">
            <div className="p-6 rounded-3xl bg-[var(--background-secondary)] border border-[var(--border)] space-y-4 shadow-xl">
              <h4 className="font-cinzel font-bold text-base text-[var(--foreground)]">
                Next Recommended Steps
              </h4>
              <div className="space-y-3 text-xs">
                <div className="p-3.5 rounded-2xl bg-[var(--background-tertiary)] border border-[var(--border)] flex items-start gap-3">
                  <CheckCircle2 className="w-4 h-4 text-[var(--green)] mt-0.5 shrink-0" />
                  <div>
                    <span className="font-bold text-[var(--foreground)]">Review Rehab Matches</span>
                    <p className="text-[var(--foreground-muted)]">Compare specialized facilities matching your physical therapy needs.</p>
                  </div>
                </div>

                <div className="p-3.5 rounded-2xl bg-[var(--background-tertiary)] border border-[var(--border)] flex items-start gap-3">
                  <UserCheck className="w-4 h-4 text-[var(--gold)] mt-0.5 shrink-0" />
                  <div>
                    <span className="font-bold text-[var(--foreground)]">Initiate Direct Placement</span>
                    <p className="text-[var(--foreground-muted)]">Let Care Coordinator dispatch your digital referral to your preferred sanctuary.</p>
                  </div>
                </div>
              </div>

              <button
                onClick={() => router.push('/patient/dashboard')}
                className="w-full py-3 rounded-xl bg-[var(--gold)] hover:bg-[var(--gold-light)] text-black font-bold text-xs shadow-md shadow-[var(--gold)]/20 transition-all hover:scale-105"
              >
                Back to Patient Portal
              </button>
            </div>
          </div>
        </div>
      </div>
    </DashboardShell>
  );
};
